export enum UserRoles {
  SUPER_ADMIN = 'SA',
  PLATFORM_ADMIN = 'PA',
  CONFIGURATOR = 'CFG',
  INSTITUTE_ADMIN = 'ADMIN',
  INSTITUTE_EMPLOYEE = 'EE',
  ASSISTANT = 'ASST',
  TEACHER = 'TCHR',
  TUTOR = 'TUTOR',
  AUTHORIZED_PERSON = 'AP',
  STUDENT = 'STU',
}
